// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxaLz26tuEyGLJpAFYVuYP4bKazB08tUM',
    appId: '1:473124177275:web:dacd6ae4bd7f45222d29de',
    messagingSenderId: '473124177275',
    projectId: 'agneepath-2024',
    authDomain: 'agneepath-2024.firebaseapp.com',
    databaseURL: 'https://agneepath-2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agneepath-2024.appspot.com',
    measurementId: 'G-QMBHFF9FGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZf1fmr45ckz3tY-P_CiEy1iXh12rcdc',
    appId: '1:473124177275:android:046e47577c5a1c852d29de',
    messagingSenderId: '473124177275',
    projectId: 'agneepath-2024',
    databaseURL: 'https://agneepath-2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agneepath-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDrSpYkxxL00RdX4saZ1cVFncapmXOcUw',
    appId: '1:473124177275:ios:feac8b1f944fee7f2d29de',
    messagingSenderId: '473124177275',
    projectId: 'agneepath-2024',
    databaseURL: 'https://agneepath-2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agneepath-2024.appspot.com',
    androidClientId: '473124177275-9lm0bpm00sa8bi4po99t1ven5kl5p4eb.apps.googleusercontent.com',
    iosClientId: '473124177275-lbeucnmdnt2ud2k1r5vlc9143mdfihd1.apps.googleusercontent.com',
    iosBundleId: 'com.agneepath.security.agneepathApp',
  );
}
